### ISSUE TITLE
是否支持redis缓存

### ISSUE THREAD

**Issue by 81pla** [edusoho/edusoho#106]
是否支持redis缓存，应该如何配置呢

在开发者文档里有搜到redis缓存开发指南，开源版应该怎么样配置使用呢？

**Comment by huang906691** [comment]
支持。
1、先在app/config/parameters.yml下添加Redis配置信息；
`parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: edusoho
    database_user: root
    database_password:
    locale: zh_CN
    secret: 79rxerux93goo88kckwo0k8gk4s4skc
    #Redis配置信息
    redis_host: 127.0.0.1:6379
    redis_password: yourPassword
    redis_timeout: 2
    redis_reserved: NULL
    redis_retry_interval: 2`

2、去app/AppKernel.php的registerCacheServiceProvider方法下新增redis的配置；
`protected function registerCacheServiceProvider($biz)
    {
        if ($this->getContainer()->hasParameter('redis_host')) {
            $biz->register(
                new Codeages\Biz\Framework\Provider\RedisServiceProvider(),
                array(
                    'redis.options' => array(
                        'host' => $this->getContainer()->getParameter('redis_host'),
                        'password' => $this->getContainer()->getParameter('redis_password'),
                        'timeout' => $this->getContainer()->getParameter('redis_timeout'),
                        'reserved' => $this->getContainer()->getParameter('redis_reserved'),
                        'redis_interval' => $this->getContainer()->getParameter('redis_retry_interval'),
                    ),
                    'dao.cache.enabled' => true,
                )
            );
        }
    }`
