### ISSUE TITLE
视频怎么加密？？

### ISSUE THREAD

**Issue by SinoMiles** [edusoho/edusoho#128]
只要购买一次就可以直接下载到里面的视频。这还怎么玩？？？

**Comment by KentEduSoho** [comment]
您好，由于Web程序无法做到复杂的处理。


如果您想要高强度的加密，须要比较复杂的技术，以及非常重的计算资源。


如果是商业级别的使用，建议接入官方EduSoho教育云。&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
