### ISSUE TITLE
向插件添加更多bundle时自动注册机制的探讨

### ISSUE THREAD

**Issue by yellowbig** [edusoho/edusoho#13]
前段时间由于要写一些插件，研究了一下Es的插件相关的东西。ES的插件生成命令plugin:create会在plugins目录下生成插件，插件中会默认有一个bundle，然后使用注册命令plugins:register会做另外一些重要的事情，其中和注册bundle有关的是把插件相关信息写入data/plugin_installed.php文件，这个文件每次框架启动时会在AppKernel.php中读取，读取出所登记的插件里bundle的名字空间信息就会动态的自动生成类名并new之，而不需要手动在AppKernel.php中添加。
现在面临的问题是：plugin:create生成的插件，只会有一个bundle，名字空间也跟随插件名称固定生成，比如一个Test插件，会且只会生成这样的一个名字空间的bundle：Test\TestBundle\TestBundle。同时在AppKernel.php中读取bundle信息时，也写死了只会读取这个名字空间（相关代码$cl = "{$c}\" . substr(str_repeat("{$c}{$p}\", 2), 0, -1);其中$c为插件名称），这就造成了如果插件开发者开发的插件想要拥有一个以上的bundle，那么非在生成插件时默认生成的那些bundle就失去了自动被注册的可能，只能手动添加，但对于插件来说，考虑到用户是在云平台安装的特性，手动添加是不可能的。
这样情况下，要想依靠系统自动注册的机制，就只能每个插件只用一个（默认的）bundle了。而对于开发者来说，限制每个插件只能拥有一个bundle也不尽合理。所以就想和ES官方以及各位开发者探讨一下，是否可以有办法对上述这个矛盾有一个比较周全的解决方案？

**Comment by sunmh207** [comment]
可否描述一个场景？我感觉，对于插件来说，一个bundle就够了，不同的功能可以用目录分开。
