### ISSUE TITLE
在 v6.12.2 中，如何自定义配色方案？

### ISSUE THREAD

**Issue by Loyalsoldier** [EduSoho/EduSoho#14]
这里的 Github Repo 还未更新到 v6.12.2，但是官网已经有了。

请问可以自定义主题“简墨”的配色方案吗？如何设置？

**Comment by Wellming** [comment]
已PUSH.

**Comment by Loyalsoldier** [comment]
@Wellming 

是通过用 `LESS` 编译 `/web/assets/v2/bootstrap/less` 下的 `Bootstrap-blue.less`、`bootstrap-blue-light.less` 等文件来实现自定义颜色的吗？

那在`简墨`的主题里，进入主题管理的页面后，这套系统是怎么识别有新的主题颜色可供选择的？

或者可以讲一下，你们是怎么编译主题文件的吗？在项目里看到了CSS Comb 的痕迹……不知道还有用到什么其他工具或者插件呢？
