### ISSUE TITLE
Warning: file_get_contents(\www\edusoho-21.3.4\bootstrap/../app/config/parameters.yml): failed to open stream: No such file or directory in \www\edusoho-21.3.4\bootstrap\bootstrap_install.php on line 16

### ISSUE THREAD

**Issue by mtgq** [edusoho/edusoho#159]
安装的时候有这个错误怎么回事啊

**Comment by huang906691** [comment]
可以手动在/app/config文件下创建一个空的parameters.yml文件，再安装。比如切换到config目录下使用命令  touch parameters.yml

**Comment by mtgq** [comment]
> 可以手动在/app/config文件下创建一个空的parameters.yml文件，再安装。比如切换到config目录下使用命令 touch parameters.yml

感谢，自己解决了已经

**Comment by mtgq** [comment]
> parameters.yml

目录下已经存在 parameters.yml 文件，尝试清空之类的依然报错

**Comment by mtgq** [comment]
> 可以手动在/app/config文件下创建一个空的parameters.yml文件，再安装。比如切换到config目录下使用命令 touch parameters.yml

![image](https://user-images.githubusercontent.com/29910922/149253679-20e5907e-69fc-4c57-8788-a518fab24757.png)
定位到错误了
