### ISSUE TITLE
Fatal error: Uncaught InvalidArgumentException: The file "routing_plugins.yml" does not exist 

### ISSUE THREAD

**Issue by rinetd** [edusoho/edusoho#17]
Fatal error: Uncaught InvalidArgumentException: The file "routing_plugins.yml" does not exist (in: /var/www/html/edusoho/app/config, /var/www/html/edusoho/app/Resources). in /var/www/html/edusoho/app/cache/prod/classes.php:1525 Stack trace: #0 /var/www/html/edusoho/app/cache/prod/classes.php(2210): Symfony\Component\Config\FileLocator->locate('routing_plugins...', '/var/www/html/e...', false) #1 /var/www/html/edusoho/vendor2/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(90): Symfony\Component\HttpKernel\Config\FileLocator->locate('routing_plugins...', '/var/www/html/e...', false) #2 /var/www/html/edusoho/vendor2/symfony/symfony/src/Symfony/Component/Routing/Loader/YamlFileLoader.php(153): Symfony\Component\Config\Loader\FileLoader->import('routing_plugins...', NULL, false, '/var/www/html/e...') #3 /var/www/html/edusoho/vendor2/symfony/symfony/src/Symfony/Component/Routing/Loader/YamlFileLoader.php(91): Symfony\Component\Routing\Loader\YamlFileLoader->parseImport(Object(Symfony\Component\Routing\RouteC in /var/www/html/edusoho/app/cache/prod/classes.php on line 4475

**Comment by Wellming** [comment]
touch /var/www/html/edusoho/app/config/routing_plugins.yml
