### ISSUE TITLE
安装数据库时失败？

### ISSUE THREAD

**Issue by zhenqicai** [edusoho/edusoho#19]
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in G:\Apache24\htdocs\vendor2\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:43 Stack trace: #0 G:\Apache24\htdocs\vendor2\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php(43): PDO->__construct('mysql:host=127....', 'root', NULL, Array) #1 G:\Apache24\htdocs\vendor2\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOMySql\Driver.php(45): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=127....', 'root', NULL, Array) #2 G:\Apache24\htdocs\vendor2\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'root', NULL, Array) #3 G:\Apache24\htdocs\vendor2\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(429): Doctrine\DBAL\Connection->connect() #4 G:\Apache24\htdocs\vendor2\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion() #5 G:\Apache24\htdocs\vendor2\doctr in G:\Apache24\htdocs\vendor2\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php on line 103

**Comment by Wellming** [comment]
安装的时候，未设置数据库密码。
