### ISSUE TITLE
提示创建数据库失败

### ISSUE THREAD

**Issue by sunyang3721** [edusoho/edusoho#20]
安装的时候 配置都写好，可写权限，下一步安装等了3分钟之后就提示创建数据库失败。我以为旧版本php5.5不支持了 就安装php7版本之后继续安装，还是不行。这个到底是我的问题，还是代码问题？

**Comment by opawtech** [comment]
increase your php configuration set_time_limit() from 30 to 1000 or higher

**Comment by Wellming** [comment]
如还有此问题，请新开issue，给出完整的错误提示，以定位问题。
