### ISSUE TITLE
建议vendor目录从git管理中移除掉

### ISSUE THREAD

**Issue by slince** [edusoho/edusoho#22]
clone半天了都/(ㄒoㄒ)/~~

**Comment by Wellming** [comment]
因为edusoho提供了在线升级功能，而每个版本发布，只打包有变更的文件以减少升级包的体积。为方便比较差异，所以把vendor目录也提交到了git中。

建议使用科学上网工具后，下载代码。 稍后我们也会在国内也建立一个镜像站。
