### ISSUE TITLE
composer 引用已废弃 package

### ISSUE THREAD

**Issue by springjk** [edusoho/edusoho#25]
[endroid/qrcode-bundle](https://packagist.org/packages/endroid/qrcode-bundle) 已废弃并替换为 [endroid/qrcode](https://packagist.org/packages/endroid/qrcode)

**Comment by springjk** [comment]
使用库中的 `composer.json` 与 `composer.lock` 都无法安装依赖，在添加镜像源的情况下可以安装到已缓存的 `endroid/qrcode-bundle`，但是在使用中会存在错误，目前发现在打开文件时会报错，详细情况为重定向循环；使用官网发布的包中的 vendor 可以正常工作，但官网供下载的包中又没有 `composer.json` 文件，有任何办法可以解决这个问题吗。

**Comment by springjk** [comment]
既然 GitHub 上的不对，那就分析官网下载的版本里，分析如下：

> edusoho/vendor/codeages/plugin-bundle/composer.lock

```
"name": "codeages/biz-framework",
            "version": "v0.3.4",
            "source": {
                "type": "git",
                "url": "https://github.com/codeages/biz-framework.git",
                "reference": "856a741902459c65496bbd2886e63b63f7f16d92"
            },
```

> edusoho/vendor/codeages/biz-framework/src/Dao

```
line: 168
protected function batchCreate($method, $arguments)
```

`batchCreate` 函数我查了是 0.5.0 后加的，完全不是上面的 0.3.4，而且我查阅了 0.5.0 后的每个版本，这个函数都不在 168行，你们是用的内部库吗，为什么完全对不上，我将 `codeages` 厂商下的包全部更新到 依赖 0.5.0 后依然不对，如果你们这个和官网不同步，为什么 release 版本又完全一直，代码有不一样，版本控制完全是瞎写的吗？

`edusoho/vendor/composer/installed.json` 这里面的信息也完全不对，官网发布包里的依赖信息也被删除了，完全没法正常的使用 composer 开发。

请告知我到底该怎么做，学艺不精，比对了一天 vendor 的几千个文件没有找到结果，前辈，你们一个地方没有提交，我这里就要卡很久，希望前辈指点。🙏

**Comment by springjk** [comment]
https://packagist.org/packages/codeages/plugin-bundle
https://packagist.org/packages/codeages/biz-rate-limiter
https://packagist.org/packages/codeages/biz-framework
https://packagist.org/packages/codeages/rest-api-client

**Comment by wenqinruan** [comment]
如果要自己开发的话，建议使用github的源码。

**Comment by springjk** [comment]
@wenqinruan 我的问题应该表述的比较清楚，正是源码存在问题我才会手动比对。

**Comment by springjk** [comment]
1.使用库中的源码无法正常的 install，因为缺少sql和其他文件，没法自动创建文件夹目录
2.使用`php app/console util:init-website` 或其他命令生成站点后，在上传文件的说话会报错

而以上错误在将 vendor 换为 官网下载的库后都是好的。

**Comment by fyee** [comment]
@springjk  这个问题将在最新的relase分支上修复，产生这样的原因是由于目前EduSoho仍然需要提供5.3版本的支持，而endroid/qrcode 目前兼容的最小的版本是php5.4。我将手动维护版本以保证可以在5.3的版本上运行。开发者建议使用5.6以上的版本进行开发，即可。

**Comment by springjk** [comment]
@fyee 好的，谢谢，你的这个回答应该是针对有两个qrcode包的情况，那二楼和三楼的问题如何解决，能提供正常使用的 composer.json 吗？

**Comment by wenqinruan** [comment]
@springjk 你可以把composer.lock文件删除，然后更新你的vendor库

**Comment by springjk** [comment]
@wenqinruan 我哪里还没说清楚吗，如果更新能够解决就不会有这个 issue。

使用 GitHub 上的版本，composer update 后上传文件出现错误, 创建课程也是报错，用官网提供的文件是好的，对比发现官网用的是 包含 batchCreate 函数 0.5.0后的版本，和 github 上的composer.json 完全不符。我前面写的都没人看吗？

**Comment by springjk** [comment]
话说这个 codeages/biz-framework 作者是你吧，这个问题我描述清楚了吗？

**Comment by wenqinruan** [comment]
@springjk 我的意思是composer.json里的依赖使用最新版本，比如`codeages/biz-framework`,你可以先让自己的环境能正常工作

**Comment by springjk** [comment]
@wenqinruan 我试过将 `codeages/biz-framework` 等更新为代码匹配的 `0.5.0` 之后，然后代码就不能正常工作了，我记得是打开页面提示需要四个参数传入的参数不够不正确，因为个人能力以及时间问题无法去继续长时间跟进，现在我已经被迫更换为官网的发布版本并且将 vender 完全纳入版本库，并且因为没有 composer.json 我无法使用任何 packagist，总而言之在使用上非常不友好，我不了解你们内部的版本发布流程，但就我目前所知，我个人对此有一些不成熟的建议：

1. 如果你们不是修改过 vendor 而仅仅是为了比对文件，是不是存在其他更好的方法来比对；
2. GitHub 上的代码请感觉根本就是没经过测试的，版本号和官网一致但是代码根本不一致，希望保持正确的更新和包含正确的 composer.json；
3. 如果2不能实现那么请在官网发布的版本中包含正确的 composer.json；
4. 如果确实要用到某个已经废弃并且下载不到的 package，我的建议是自己去提交发布一份然后使用，比如 [vinzcoco/qrcode-bundle](https://github.com/vinzcoco/qrcode-bundle),可以自己去 packagist 发布或者使用 [VCS repository](https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository)。

以上是我认为体面一点的做法，仅此。

**Comment by wenqinruan** [comment]
@springjk 感谢您宝贵的建议，给您带来这么长的时间困扰，我深表歉意。我们以后会规范发布流程：

- 保持官网的代码和 GitHub 的代码是一致的。

- 确保 GitHub 的代码可以直接用来开发。
