### ISSUE TITLE
/web/install/start-install.php脚本里写权限检查的目录列表里多数目录不存在

### ISSUE THREAD

**Issue by furaoing** [edusoho/edusoho#27]
$paths = array(
        'app/config/parameters.yml',
        'app/data/udisk',
        'app/data/private_files',
        'web/files',
        'web/install',
        'app/cache',
        'app/data',
        'app/logs',
    );

is_executable这个函数只有当文件存在，并且有x权限的时候才返回true

除了web/install以外，其他目录在源码树里均不存在，导致权限检查失败，安装无法继续

**Comment by springjk** [comment]
这里缺少自动检查创建，在一个名为 `init` 的命令里有，但是会出现其他问题。所以我目前的安装是这样的，供参考：
```
cp app/config/parameters.yml.dist  app/config/parameters.yml
mkdir -p app/data/udisk app/data/private_files web/files web/install app/cache app/data app/logs
chmod 755 app/config/parameters.yml
```

**Comment by fyee** [comment]
@springjk  @furaoing  

你们用的是哪个版本安装的？ 是否是在github下载？github的上开发的版本，不是生成版本，所以安装方式不一样。

按照你们的描述，应该使用生产环境安装安装Edusoho。请从这里下载生产环境的版本：[http://www.edusoho.com/open/show](http://www.edusoho.com/open/show)

开发环境下安装教程参考：
[http://developer.edusoho.com](http://developer.edusoho.com)
