### ISSUE TITLE
在MacOS的Firefox无法运行

### ISSUE THREAD

**Issue by marcoziti** [edusoho/edusoho#30]
你好，

我尝试运行stuq.org上海的edusoho来学习一门课程。发现在MacOS上面的Firefox里面无法正常运行。当我尝试在safari里面运行页面的时候，看到提示安装消息“您的浏览器未装Flash播放器或版本太低，请先安装Flash播放器。点击安装”。但是Firefox里面并没有该提示。而且我的Firefox已经激活了flash。

Firefox版本信息：55.0.3 (64-bit)
MacOS把本信息：10.12.6 (16G29) 这两天就升级10.13了。

谢谢

**Comment by fyee** [comment]
你好，感谢反馈这个问题，我们将于近期修复

**Comment by benvirus** [comment]
@marcoziti 您好，首先非常感谢您的反馈。经过查看，您反馈的bug未能复现。
恳请您提供更详细的信息。如：
1、不能观看的视频的地址。
2、是否出现报错。报错信息是什么。
3、如果方便，请提供控制台 console 的报错截图。
进一步的沟通，可以联系我QQ： 645314193
