### ISSUE TITLE
system:init no file app/data/crontab_config.yml

### ISSUE THREAD

**Issue by Andy-Yuen** [edusoho/edusoho#32]
[Symfony\Component\Debug\Exception\ContextErrorException]                                                         
  Warning: fopen(/www/wwwroot/edusoho-8.2.5/app/../app/data/crontab_config.yml): failed to open stream: No such file or directory

**Comment by BrentChen** [comment]
需要手动新建这个文件，
后面会提供一个 脚本，帮助初始化项目，等完成后，会在这个issue上追加描述

**Comment by BrentChen** [comment]
已经有安装教程了，不再提供相应的脚本
