### ISSUE TITLE
这 api 乱的也是没谁了 ヽ(ー_ー)ノ

### ISSUE THREAD

**Issue by Andy-Yuen** [edusoho/edusoho#33]
遍地都是 api o(╥﹏╥)o
api\config\routing.php
ApiBundle/Controller/ prefix: /api
opxiaMobileBundleV2/Resources/config/routing.yml  prefix:/mapi_v2
还有一个废弃的 TopxiaMobileBundle

**Comment by BrentChen** [comment]
目前来说 api 有3种

**Comment by l1l31** [comment]
`ApiBundle/Controller/ prefix: /api` 用这个，其他的都是要废的。
