### ISSUE TITLE
安装向导出错

### ISSUE THREAD

**Issue by liyuliang2013** [edusoho/edusoho#35]
3. 初始化系统
怎么少了一个列呢？

An exception occurred while executing 'SELECT * FROM user WHERE uuid = ? LIMIT 1 ' with params ["91a79bcaadd56334789fc753047e122ae972e88e"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'uuid' in 'where clause'

**Comment by BrentChen** [comment]
什么情况下 会出这个问题？

新装环境不会报错
命令 
bin/phpmig migrate
app/console system:init

migrations 中 20180206163424_user_add_uuid.php 会加这个字段

**Comment by birdy0815** [comment]
执行 bin/phpmig migrate 还没到2018年的就直接报错了
