### ISSUE TITLE
视频文件的存储以及转码工作支不支持传给七牛或者又拍云

### ISSUE THREAD

**Issue by slince** [edusoho/edusoho#36]
视频放在本地进行处理以及下载对带宽和服务器硬件都是个挑战。。。

**Comment by l1l31** [comment]
EduSoho有教育云，可以了解下。管理后台顶部菜单中就有。

**Comment by slince** [comment]
@l1l31  这个单机版的支持吗

**Comment by BrentChen** [comment]
抱歉，我们只支持教育云

**Comment by Qijin1** [comment]
这个提问关闭了吗？

**Comment by KentEduSoho** [comment]
官方的视频就有 价格便宜&nbsp;



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月2日(周六) 凌晨0:52
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [edusoho/edusoho] 视频文件的存储以及转码工作支不支持传给七牛或者又拍云 (#36)




 
这个提问关闭了吗？
