### ISSUE TITLE
php app/console cache:clear 报错

### ISSUE THREAD

**Issue by forkitonline** [edusoho/edusoho#37]
$ php app/console cache:clear -vvv

 // Clearing the cache for the dev environment with debug true                                                          

 // Clearing outdated warmup directory...                                                                               

 // Warming up cache...                                                                                                 

                                                            
  [Symfony\Component\Debug\Exception\FatalThrowableError]   
  Call to a member function getSchemeAndHttpHost() on null  
                                                            

Exception trace:
 () at /Users/liyuliang/code/php/edusoho-git/app/AppKernel.php:147
 AppKernel->initializeBiz() at /Users/liyuliang/code/php/edusoho-git/app/AppKernel.php:53
 AppKernel->boot() at /Users/liyuliang/code/php/edusoho-git/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:134
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() at /Users/liyuliang/code/php/edusoho-git/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:96
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at /Users/liyuliang/code/php/edusoho-git/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:267
 Symfony\Component\Console\Command\Command->run() at /Users/liyuliang/code/php/edusoho-git/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:872
 Symfony\Component\Console\Application->doRunCommand() at /Users/liyuliang/code/php/edusoho-git/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:191
 Symfony\Component\Console\Application->doRun() at /Users/liyuliang/code/php/edusoho-git/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:92
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /Users/liyuliang/code/php/edusoho-git/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:122
 Symfony\Component\Console\Application->run() at /Users/liyuliang/code/php/edusoho-git/app/console:32

cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>

**Comment by BrentChen** [comment]
Thanks, we will fix it before next Friday

**Comment by BrentChen** [comment]
抱歉，问题还没解决，我们先把任务列入 backlog，解决后再将此问题关闭

**Comment by BrentChen** [comment]
这个命令是 symfony自带命令，我们edusoho不使用此命令，我们的cache 目录就在 app/cache 下，直接删除该目录即可
