### ISSUE TITLE
关于HTTPS的疑问

### ISSUE THREAD

**Issue by asseywang** [edusoho/edusoho#38]
我测试站点 开通了HTTPS之后，遇到405问题
http请求返回405 (Method Not Allowed).
jquery.js:3 Mixed Content: The page at 'https://www.abc.net/admin/setting/optimize' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.abc.net/admin/setting/optimize/remove-cache'. This content should also be served over HTTPS.

还有修改用户等操作同样有这个问题，请问下之前有人遇到这个问题吗？如何解决？

**Comment by asseywang** [comment]
这个链接是清除缓存时报错的

**Comment by BrentChen** [comment]
nginx 服务器吗， 服务配置是怎样的？ 你是直接访问 https://www.abc.net/admin/setting/optimize 这个页面报错的？

**Comment by asseywang** [comment]
点击清除缓存按钮，我查的资料说是，hTTPS下 Nginx不允许操作静态文件执行，所以会报405

**Comment by BrentChen** [comment]
我们的测试站没这个问题
应该是哪里配错了，看一下这个链接  http://www.qiqiuyu.com/article/889
