### ISSUE TITLE
低版本Chrome浏览器在播放课程的时候请求会有pending状态

### ISSUE THREAD

**Issue by hrbxb** [edusoho/edusoho#39]
播放时间延迟比较厉害，最新Chrome版本不会出现此问题。
Stalled的时间会有20多秒
在最新的QQ浏览器(Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.26 Safari/537.36 Core/1.63.5514.400 QQBrowser)，或者是360安全浏览器(Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36)都会有这个问题。

Request URL:http://elearning.ssgaga.com/player/2/file/vIpZXo3q71taNHqalFQZFgyNIzQ6BRbm
Referrer Policy:no-referrer-when-downgrade
Request Headers
Provisional headers are shown
Referer:http://elearning.ssgaga.com/course/7/task/10/activity_show
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.26 Safari/537.36 Core/1.63.5514.400 QQBrowser/10.1.1628.400
X-Requested-With:ShockwaveFlash/27.9.9.999

**Comment by hrbxb** [comment]
http://fex.baidu.com/blog/2015/01/chrome-stalled-problem-resolving-process/

**Comment by BrentChen** [comment]
上面的分析很有参考价值，我们内部看一下这个问题

**Comment by BrentChen** [comment]
1.经过查证，该网站使用的是本地视频，本地视频使用的不是云视频播放器
2.使用videojs播放器的时候，常见的Chrome firefox 如果是视频，会默认使用H5 <video> 播放，如果不支持才会询问客户是否启用flash
3.QQ浏览器10+ 内置flash 插件，默认启用加载，所以在加载视频播放页面的时候，默认使用flash 播放，低于10版本的浏览器可以通过 qqbrowser://plugins/ 禁用flash；高于10版本无设置入口
4.360浏览器内置flash 插件，默认启用加载，所以在加载视频播放页面的时候，默认使用flash 播放，可以通过se://plugins/ 禁用flash

**Comment by BrentChen** [comment]
即：
本地视频下，QQ浏览器和360浏览器默认会启用flash播放，禁用浏览器flash则没问题；
云视频下，会直接使用h5播放器;
