### ISSUE TITLE
初始化失败

### ISSUE THREAD

**Issue by sunson468** [edusoho/edusoho#45]
[InvalidArgumentException]
  Duplicate migration, "D:\Projects\mandao\mandaotech\source\mandao-edu\migrations\20161014163431_Init.php" has the same version as "Init"

PHP7.3 

用8.3.1版本在线安装没问题，就是用master的分支自己初始化开发环境不行

而且执行bin/phpmig migrate也是直接打印结果

必须执行vendor目录下的，难道是php版本太高了么？

**Comment by sunson468** [comment]
初步确定是window的path分隔符规则不同造成的

**Comment by sunson468** [comment]
就是window的path符的问题

**Comment by open1024** [comment]
请问具体如何解决了？谢谢！
