### ISSUE TITLE
执行npm run compile报错

### ISSUE THREAD

**Issue by sunson468** [edusoho/edusoho#46]
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

**Comment by LianJion** [comment]
你好，能描述一下本地的环境吗？ 电脑系统，node版本，yarn版本， edusoho开发分支，我基于develop分支 webpack能够正常跑起来

**Comment by sunson468** [comment]
> 你好，能描述一下本地的环境吗？ 电脑系统，node版本，yarn版本， edusoho开发分支，我基于master分支 webpack能够正常跑起来

`18 verbose node v10.11.0
19 verbose npm  v6.5.0
20 error code ELIFECYCLE
21 error errno 1
22 error es-webpack-engine@1.0.0 compile: `cross-env NODE_ENV=production node --max_old_space_size=4096 node_modules/es-webpack-engine/dist/webpack.prod.js --parameters webpack.config.js`
22 error Exit status 1`

**Comment by sunson468** [comment]
> 你好，能描述一下本地的环境吗？ 电脑系统，node版本，yarn版本， edusoho开发分支，我基于master分支 webpack能够正常跑起来

> 操作系统是windows10 64位  

> node版本     10.11.0

> edusoho版本：master

>  yarn：1.10.1

**Comment by LianJion** [comment]
你好，我已经在window10上复现了这个问题，目前已经在处理阶段，等有了解决方案会及时告知，谢谢。

**Comment by LianJion** [comment]
你好，window10上“报错”问题解决了，解决方案如下：
    1 修改edusoho根目录的package.json中的“es-webpack-engine”版本号为“3.5.3-rc.2”
            "es-webpack-engine": "3.5.3-rc.2"
   2 删除 node_modules
   3 重新安装依赖 —— yarn 
   4 执行 yarn run dev/compile (对应开发/编译模式)， 不会报错
