### ISSUE TITLE
安装没成功就报错了

### ISSUE THREAD

**Issue by feverrun** [edusoho/edusoho#47]
错误信息如下：
An exception occurred while executing 'SELECT * FROM user WHERE uuid = ? LIMIT 1 ' with params ["0aa36eb8d142c67e2d5d34963f90b2a488a71845"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'uuid' in 'where clause'

**Comment by sunson468** [comment]
migrations目录下面自己找，有一个补丁包里就有

**Comment by quocnho** [comment]
Error when installing Unknown column 'uuid' in 'where clause' in version 8.3.20 release
