### ISSUE TITLE
Error when installing Unknown column 'uuid' in 'where clause' release v.3.8.20

### ISSUE THREAD

**Issue by quocnho** [edusoho/edusoho#53]
Edusoho v8.3.20 
An exception occurred while executing 'SELECT * FROM user WHERE uuid = ? LIMIT 1 ' with params ["04d8a0b75d629c541d9fe72a1e6413490b3515a4"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'uuid' in 'where clause'

**Comment by yexuhui17** [comment]
There are 2 ways to install edusoho.
1.  download package from official site http://dl.edusoho.com/edusoho-release/edusoho-8.3.20.tar.gz and install through the web UI.
2. clone source code from github and install through command line.

could you please let me know which way you install and which install guide you followed?

**Comment by quocnho** [comment]
Thanks, I have already installed system successful. But your link can not download. I download source from admin5.com. Thanks any way!

**Comment by yexuhui17** [comment]
> Thanks, I have already installed system successful. But your link can not download. I download source from admin5.com. Thanks any way!

Okay. Could you please provide more info about how you fix the issue?  Did you change codes or download a new package? This will help us to solve this issue thoroughly. Thanks~
