### ISSUE TITLE
请问edusoho 支持mysql8.0.11版本么？ 

### ISSUE THREAD

**Issue by feverrun** [edusoho/edusoho#55]
请问edusoho 支持mysql8.0.11版本么？

**Comment by bellorchid** [comment]
mysql 8.0+版本默认开启`only_full_group_by`模式，如果想在在8.0+下运行，需要在mysql 的`sql-mode` 中去掉此项，我们也会在持续迭代中增加EduSoho中对`only_full_group_by`语句限制的支持

**Comment by bellorchid** [comment]
EduSoho 8.6.4 版本已经解决MySQL8.0关键词、严格模式等问题，您现在可以在EduSoho 8.6.4以及以上版本使用MySQL8.0数据库
