### ISSUE TITLE
edusoho迁移另外的服务器不能访问

### ISSUE THREAD

**Issue by developers-youcong** [edusoho/edusoho#63]
错误描述:
参考文档:http://www.qiqiuyu.com/my/course/331
按照这上面的进行迁移，由A服务器迁移到B服务器或者是由Linux迁移到Windows发现不能访问。
效果图如下:
![image](https://user-images.githubusercontent.com/45055576/59894817-9c0f0e80-9414-11e9-99a4-03746a4726a8.png)

由图可知，访问还是一片白板，删缓存了也改数据源配置，数据源配置设置为动态的形式(mysql也远程授权了)，如图:
![image](https://user-images.githubusercontent.com/45055576/59894891-e1cbd700-9414-11e9-8e11-76b823c19ec8.png)

最后还是不能本地windows访问Edusoho及其另外一台Linux服务器访问Edusoho，请问是什么原因呢？

如果是去官网下载后解压一遍，通常是没有问题的，但是如果那样的话，岂不是非常不灵活，比如我本地windows中的Edusoho增加某某功能后，然后我还需要再在Linux上再改一遍，这样岂不是非常麻烦。我觉得通常windows改一遍通过git上传到linux上基本就可以了(当然了，中间也许可能需要修改如数据源之类的配置等)

**Comment by yexuhui17** [comment]
可以尝试下改成开发模式页面就不会是空白了 一般会有详细的错误信息显示, 方便下一步排查。  修改方法: nginx 入口文件从app.php 改成 app_dev.php

**Comment by developers-youcong** [comment]
我的web服务器是apache

**Comment by developers-youcong** [comment]
我改为开发模式，如图:
![image](https://user-images.githubusercontent.com/45055576/59895691-25741000-9418-11e9-9f33-646bcde3cd0d.png)
同时我也重启了apache和php。但是仍然和原来的一样。没有区别（也就是访问时变为空白）

**Comment by yexuhui17** [comment]
apache 可以在  web/.htaccess 中修改开发模式，改完记得删除app/cahce 注意目录权限

**Comment by developers-youcong** [comment]
我用的Edusoho版本为(8.3.30)最新版，apache为2.4,php位7.0。

**Comment by developers-youcong** [comment]
嗯，好的，我试试看，谢谢。

**Comment by developers-youcong** [comment]
修改web/.htacess，如图
![image](https://user-images.githubusercontent.com/45055576/59899085-fd8ba900-9425-11e9-9cc7-049e6bd09555.png)
将.htacess中的app.php全部改为app_dev.php，修改完后，访问效果图如下:
![image](https://user-images.githubusercontent.com/45055576/59899134-362b8280-9426-11e9-9ac7-e0d0d830b6a0.png)

报错信息翻译过来的意思是:不允许您访问此文件。有关更多信息，请查看app_dev.php。

另外，app_dev.php和app.php之间的主要区别在于如下:
![image](https://user-images.githubusercontent.com/45055576/59899256-acc88000-9426-11e9-8372-ad1f053336cd.png)

而且我也有将cache目录的缓存删除

补充问一下，以下面这张图为例:
![image](https://user-images.githubusercontent.com/45055576/59899410-29f3f500-9427-11e9-8f19-09ffc7ed1121.png)

假定我在一个叫www.test001.com服务器安装官方文档那样安装好了后，于是我将其上传到对应的阿里云仓库上，这时我觉得我需要修改www.test001.com上面edusoho，但是Linux上修改不方便，于是我将其弄到本地上，也是参考文档上删除缓存改数据库配置(如果是我上面那张图的话，只要数据库远程授权过了，就不会影响正常数据库访问，Node.js、Java、Python都是这样的。之前我研究过一个CRMEB也是如此。
但是换成Edusoho就不行了。我觉得很奇怪。而且访问一片空白，让人觉得似乎被拦截或者是没有权限访问。暂且先不说windows本地，我将其放到www.test002.com服务器上，还是一样，和windows一样(访问空白)，换言之，如果是去官方网站上重新下载一个edusoho并解压重新安装却是可以的，但是如果是那样的话就没有意义了。

还有就是我在Linux上通过查询日志，发现如下错误信息(每次在浏览器上访问都会有这样的一条信息，该日志位于/var/www/edusoho/app/logs目录):
[2019-06-21 13:24:16] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Loader: The "/var/www/edusoho/app/../plugins" directory does not exist ("/var/www/edusoho/app/../plugins"). at /var/www/edusoho/vendor/twig/twig/lib/Twig/Loader/Filesystem.php line 101) {"exception":"[object] (Twig_Error_Loader(code: 0): The \"/var/www/edusoho/app/../plugins\" directory does not exist (\"/var/www/edusoho/app/../plugins\"). at /var/www/edusoho/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:101)"} []

翻译过来，总的意思是目录不存在，关于这一点我很疑惑。

另外业务方面的日志(biz.log)，打印的信息，也正常，如图所示:
![image](https://user-images.githubusercontent.com/45055576/59899872-ebf7d080-9428-11e9-9c4e-cea98fa581d5.png)

**Comment by yexuhui17** [comment]
感觉你快解决了
1. not allow to access this file.   在app/data/下创建一个dev.lock 文件，安全考虑后续问题解决切换回生产模式后再删掉
2."/var/www/edusoho/app/../plugins" directory does not exist 。  检查下 这个plugins目录是否存在，有可能是经过linux -> windows -> linux 后 有些原来在linux上的软连失效了，建议linux -> linux这样迁移。或者真要通过windows，可以先打个tar.gz

**Comment by developers-youcong** [comment]
问题已经解决非常感谢你的热情协助。

问题解决方式是你说的情况二(没有这个plugins目录的存在）,我在windows和Linux上添加对应的plugins,然后就可以看到对应的效果了。也就是只需增加plugins这个目录即可。但是我不太明白为什么要增加这个plugins。plugins目录，我想通常主要是放一些插件的地方，可能是源码中某些地方需要调用。

windows:
![image](https://user-images.githubusercontent.com/45055576/59906182-a6dc9a00-943a-11e9-9d45-fdc419e7e18e.png)

Linux:
![image](https://user-images.githubusercontent.com/45055576/59906266-e30ffa80-943a-11e9-911b-a19063a1e402.png)
