### ISSUE TITLE
Edusoho修改页面无效

### ISSUE THREAD

**Issue by developers-youcong** [edusoho/edusoho#66]
问题描述:
我修改Edusoho项目中位于app\Resources\views\login\index.html.twig的文件发现没有效果。如图:
![image](https://user-images.githubusercontent.com/45055576/60480261-81ae1e00-9cbb-11e9-9ac5-f53a7ddef7f3.png)
正常效果应该会在对应的页面弹出alert，但是并没有。

而我在另外一个symfony项目中添加如下内容，如图(却是可以正常弹出alert):
![image](https://user-images.githubusercontent.com/45055576/60480292-b02bf900-9cbb-11e9-92f6-dfe98c2b9708.png)

我也参考对应的官方文档，地址为:
http://developer.edusoho.com/frontend/intro.html

写的也不是特别详细，没有把前端如何本地调试和编译打包说清楚。

我在这里想表达的是，不管是写javascript代码还是修改部分html，在Edusoho中都无效，想问一下是什么原因？我想知道如何修改对应的twing直接可以在界面上看到对应的效果？现在无论怎么修改任何效果都看不到。

**Comment by developers-youcong** [comment]
问题已解决，主要原因是因为app/cache缓存的缘故，只需将cache文件夹清空即可。

**Comment by mtgq** [comment]
> 问题已解决，主要原因是因为app/cache缓存的缘故，只需将cache文件夹清空即可。

每次都清除好麻烦啊

**Comment by lileiseven** [comment]
本地开发，可以开启dev模式，会自动清除缓存。

**Comment by mtgq** [comment]
> 本地开发，可以开启dev模式，会自动清除缓存。

正在学习中

**Comment by KentEduSoho** [comment]
只要把开发者模式打开，就不需要手动删除了。生产环境记得关掉



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月3日(周四) 中午1:49
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [edusoho/edusoho] Edusoho修改页面无效 (#66)




  
问题已解决，主要原因是因为app/cache缓存的缘故，只需将cache文件夹清空即可。
  
每次都清除好麻烦啊
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
