### ISSUE TITLE
plugin:register命令不会把public资源目录移动到web目录下的bug

### ISSUE THREAD

**Issue by shinigamisakuragi** [edusoho/edusoho#77]
命令行安装插件时，`plugin:register`命令虽然会执行`assets:install`命令来加载静态资源，但是这时候，`assets:install`命令中`$this->getContainer()->get('kernel')->getBundles()`方法返回的bundles数组是不包含当前安装的插件的，这会导致插件内public静态资源无法访问。

**Comment by bellorchid** [comment]
开发环境下，不需要拷贝目录，public的静态资源目录是通过软链接链接到web目录下的

**Comment by shinigamisakuragi** [comment]
我的意思是插件内public目录没有软链接到web目录下，因为安装插件的时候getBundles方法不会返回当前插件，plugin:register命令中asstest:install命令就没办法进行软连接操作

**Comment by bellorchid** [comment]
命令行注册插件，executeScript函数调用安装脚本，BaseInstallScript安装脚本中已经创建软链，后面的`installAssets`是覆盖一遍当前的所有bundles注册过程，由于缓存问题扫描不到当前要注册的插件，但是因为安装脚本已经执行过，所以获取不到要注册的插件的bundles也无问题，软链仍然会正常创建
