### ISSUE TITLE
error

### ISSUE THREAD

**Issue by pearfang** [edusoho/edusoho#78]
安装引导第三步时，报An exception occurred while executing 'update user set roles ="|ROLE_USER|ROLE_TEACHER|" where id = 1': SQLSTATE[42S02]: Base table or view not found: 1146 Table 'edusoho.user' doesn't exist

**Comment by kintgy** [comment]
我们这边测试没出现这种情况，请再次检查一下有无操作，如还有疑问，请提供更多错误细节

**Comment by chinahuxiaobai** [comment]
EduSoho8.3.10安装方式（亲测可以）   请参考这个  亲测可以
