### ISSUE TITLE
symfony2.8官方已经停止维护了，有升级的计划吗

### ISSUE THREAD

**Issue by kunl** [edusoho/edusoho#86]
Symfony 2.8

Status:
Unmaintained
Released:
November 2015
End of bug fixes:
November 2018
End of security fixes:
November 2019
Latest version: 2.8.52  Code  Documentation  Changelog  New features

 This was a long-term support version.

**Comment by bellorchid** [comment]
您好，短时期内EduSoho还要支持php53环境，我们已经在准备分析php各版本客户的占比，计划逐渐放弃对低版本php支持了，等到环境的问题解决之后，会去考虑对symfony依赖的的改造或者升级
