### ISSUE TITLE
github版是否故意屏蔽掉了admin的静态资源了呢

### ISSUE THREAD

**Issue by kunl** [edusoho/edusoho#90]
如图，后台依赖的这些静态文件并没有，是出于什么原因呢

![image](https://user-images.githubusercontent.com/2870324/74225970-a1e49780-4cf6-11ea-838c-e90eb6d729e0.png)

**Comment by Guogongwei** [comment]
是通过软链接生产的，尝试命令行运行  php app/console assets:install web --symlink --relative

**Comment by kunl** [comment]
php app/console  system:init 也可以
