### ISSUE TITLE
普通课程与班级课程不能实时同步的bug！！！

### ISSUE THREAD

**Issue by libaoyu1981** [edusoho/edusoho#94]
创建完普通课程并发布，再将其加入班级课程。之后再修改普通课程，对应的班级课程会存在不能实时同步的问题，等多久都不能同步。
1.普通课程新增了课时的情况，班级课程不会新增。
2.普通课程修改了课时内容的情况，班级课程不会变化。
3.普通课程修改了课时标题，班级课程会自动更新。

请各位高手指点，谢谢。

**Comment by Guogongwei** [comment]
检查下定时任务是否正常， 部分同步业务是通过定时任务进行的

**Comment by libaoyu1981** [comment]
感谢您这么快的回复，没去定时任务是正常的，因为标题修改都可以同步过来，目前是新增课时和修改课时内容，班级课程无法自动更新，应该是bug，我下载了最新版本git库代码，多次测试的结果，请您帮忙再看下，谢谢。

**Comment by libaoyu1981** [comment]
抱歉，这个不是bug，是user表缺少一个type字段为system的专用job用户。初始化应该有这行记录，我可能手工删掉了，导致了这个问题。edusoho的代码还是很优秀的，稳定性也很好，加油！
